name: CI

on: [push]

jobs:
  run-docker-action:
    runs-on: ubuntu-latest 
    steps:
      - name: list dir
        run: ls -la
      - name: Run Docker-based Action
        uses: ./
        with:
          message: 'Hello, Docker!' 
      - name: list dir
        run: ls -la
