name: node-test
on: 
  push:
    
jobs:
  test-job:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest,macos-lates]

    runs-on: ${{ matrix.os }}
    steps:
      - name: get repository
        uses: actions/checkout@v4
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: run script
        run: node app.js
