name: CI

on: [push]

jobs:
  run-docker-action:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Docker-based Action
        uses: ./actions.yml 
        with:
          message: 'Hello, Docker!' 
