name: CI

on: [push]

jobs:
  run-docker-action:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: pwd
        run: |
          ls -ls 
          pwd
      - name: Run Docker-based Action
        uses: ./
        with:
          message: 'Hello, Docker!' 
